runtime: nodejs20
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
# Nota: Para asegurar la IP estática en GCP App Engine, 
# se recomienda usar Cloud Run con un Static IP o un conector VPC.
